# Generated by Django 5.1.5 on 2025-01-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeartReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_pressure', models.IntegerField()),
                ('max_pressure', models.IntegerField()),
                ('heart_rate', models.IntegerField()),
                ('reading_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
