# Generated by Django 5.1.5 on 2025-01-23 18:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartreading',
            name='reading_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='heartreading',
            name='reading_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
